remote_theme: jekyll/minima@master
markdown: kramdown
kramdown:
  input: GFM

plugins:
- jekyll-remote-theme
- jekyll-seo-tag
- jekyll-redirect-from


title: "DSC80 - Practices of Data Science"
description: |
  This is an academic data science project by Dimitrij Eli for the course DSC 80 — Practices of Data Science
  at the University of California, San Diego.If you’re interested, have feedback, or would like to connect, feel free to reach out.



github_username: DimitrijEli
email: dimitrij.eli@outlook.com


minima:
  skin: classic
  show_excerpts: true
  social_links:
    - title: "LinkedIn"
      icon: linkedin
      url: "https://www.linkedin.com/in/dimitrij-eli-966843257/"
    - title: "GitHub"
      icon: github
      url: "https://github.com/DimitrijEli?tab=repositories"
  nav_pages:
    - about.md
