remote_theme: jekyll/minima@master

plugins:
- jekyll-remote-theme
- jekyll-feed
- jekyll-seo-tag


title: "DSC80 - Practices of Data Science"
description: "TEST"
github_username: DimitrijEli

minima:
  skin: auto
  show_excerpts: true
  social_links:
    title: "LinkedIn"
    icon: linkedininkedIn
    url: "https://www.linkedin.com/in/dimitrij-eli-966843257/"
    title: "GitHub"
    icon: github
    url: "https://github.com/DimitrijEli"
  